version: "3.7"
services:
  mysql:
    container_name: mysql-con
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_USER_PASSWORD}
      - TZ=Asia/Seoul
    ports:
      - "3307:3306"
    volumes:
      - ./db/data:/var/lib/mysql



#  redis:
#    container_name: redis-con
#    image: redis:








#networks:
#  backend-net: # 이후 backend-net은 모두 expose로 변경
#    driver: bridge
#  frontend-net:
#    driver: bridge